---
output: 
  pdf_document:
    keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex
    includes:
      in_header: preamble.tex
geometry: margin=1in

bibliography: ../library.bib
csl: ../apa.csl

title: "Quantitative Portfolio Management"
author: Patrick Hénaff
date: "Feb 2021"
email: "pa.henaff@gmail.com"

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
   - \usepackage[utf8]{inputenc}
   - \usepackage{amsthm}
   - \usepackage{xfrac}
---

```{r setup, include=FALSE, cache=F, message=F, warning=F, results="hide"}
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache.path='_cache/')
knitr::opts_chunk$set(warning=F, message=F)
```

\newcommand{\ones}{\mathbf{1}}
\newcommand{\onesT}{\mathbf{1}^T}

\newtheorem{thm}{Theorem}

In this short note, we summarize the mathematical elements of the classical portfolio theory of Markowitz and Trenor-Black.

# Arithmetic vs. Geometric mean

Let $r_A$ and $r_G$ be, respectively, the arithmetic and geometric means of a series of returns:

\begin{align*}
r_A &= \frac{1}{n} \sum_{k=1}^n r_k \\
r_G &= \prod_{k=1}^n (1+r_k)^{1/n} - 1
\end{align*}

and let $V$ be the variance of $r_k$. We show that the geometric mean, which correctly represents the increase in wealth from an investment, is lower than the arithmetic mean.

The MacLaurin series for $(1+x)^{1/n}$ is:

$$
(1+x)^\frac{1}{n} = 1 + \frac{1}{n} x + \frac{1-n}{n^2} \frac{x^2}{2} + o(x^2)
$$


$$
r_G \approx \prod_{k=1}^n \left(1 + \frac{1}{n} r_k + \frac{1-n}{n^2} \frac{r_k^2}{2} \right) - 1
$$

Developping the product and keeping terms of order 2,

$$
r_G \approx \frac{1}{n} \sum_k r_k + \frac{1}{n^2} \sum_{k \neq l} r_k r_l + \frac{1-n}{2n^2} r^2_k
$$

\begin{align}
r_G & \approx r_A - \frac{1}{2} \left[ \frac{1}{n} \sum_k r^2_k - \frac{1}{n^2} \left( \sum_k r^2_k + 2 \sum_{k \neq l} r_k r_l \right) \right] \\
& \approx r_A - \frac{1}{2} \left[ \frac{1}{n} \sum_k r^2_k - \left(  \frac{1}{n} \sum_k r_k  \right)^2 \right] \\
& \approx r_A - \frac{1}{2} V, \ \ V >= 0
\end{align}



# Quadratic Programming

## QP with equality constraints

$$
\begin{aligned}
    \mbox{min} \ \ & w^T \Sigma w  \\
    \mbox{s.t.} & \\
    & A^T w  = b
  \end{aligned}
$$

Lagrangian:

$$
L(w, \lambda) = \frac{1}{2} w^T \Sigma w - \lambda^T \left(A^Tw -b \right)
$$

First order conditions:

$$
\left\{
                \begin{aligned}
                \Sigma w - A \lambda &= 0 \\
                A^Tw & = b
                \end{aligned}
              \right.
$$

or,

$$
\begin{bmatrix} \Sigma & -A \\ A^T & 0 \end{bmatrix}  \left[ \begin{array}{c} w \\ \lambda \end{array} \right] = \left[ \begin{array}{c} 0 \\ b \end{array} \right] 
$$


## Special case of Minimum Variance problem

$$
A = \begin{bmatrix} 1  \\ \vdots  \\ 1\end{bmatrix} \ \ \ b = \mu^*
$$

Solution:

$$
w = \lambda \Sigma^{-1} A
$$

Normalize so that weights sum to 1:

$$
w = \frac{\Sigma^{-1} \mathbf{1}}{\mathbf{1}^T\Sigma^{-1}\mathbf{1}}
$$

# Mean-Variance model [@Markowitz1952]

$$
\begin{aligned}
    \mbox{min} \ \ & \frac{1}{2} w^T \Sigma w  \\
    \mbox{s.t.} & \\
    \mathbf{1}^Tw & = 1 \\
        R^Tw & = R_P
  \end{aligned}
$$

Lagrangian:

$$
L(w, \lambda_1, \lambda_2) = \frac{1}{2} w^T \Sigma w - \lambda_1(\mathbf{1}^Tw-1) -\lambda_2(R^Tw - R_P)
$$

Solution of first order conditions:


\begin{equation}
\left\{
                \begin{aligned}
                \Sigma w - \lambda_1 \mathbf{1} -\lambda_2 R  &= 0 \label{eq:eq-1} \\
                \mathbf{1}^T w &= 1 \\
                R^Tw & = R_P
                \end{aligned}
              \right.
\end{equation}

Determination of $\lambda_1$ and $\lambda_2$:

$$
w = \Sigma^{-1} (\lambda_1 \mathbf{1} + \lambda_2 R)
$$

Define:


\begin{align*}
                a & = \onesT \Sigma^{-1} \ones \\
                b & = \onesT \Sigma^{-1} R \\
                c & = R^T \Sigma^{-1} R 
                \end{align*}


Substitute in (\ref{eq:eq-1}):

\begin{equation*}
\left\{
                \begin{aligned}
                \lambda_1 a + \lambda_2 b & = 1 \\
                \lambda_1 b + \lambda_2 c & = R_P
                \end{aligned}
              \right.
\end{equation*}

Solution:

\begin{align*}
                \lambda_1 & = \frac{c - b R_P}{\Delta} \\
                \lambda_2 & = \frac{a R_P - b}{\Delta} \\
                \Delta & = ac - b^2
                \end{align*}


Note that:

\begin{align*}
\sigma^2_P & = w^{*T} \Sigma w^* \\
& = w^{*T} \Sigma \left( \lambda_1 \Sigma^{-1} \ones + \lambda_2 \Sigma^{-1} R \right) \\
& = \lambda_1 + \lambda_2 R_P
\end{align*}

Two remarkable solutions:

+ Minimum variance portfolio

\begin{align*}
\frac{\partial \sigma^2_P}{\partial R_P} & = 0 \implies \\
\frac{2 a R_P - 2b}{\Delta} & = 0 \implies \\
R_P & = \frac{b}{a} \\
\sigma^2_P &= \frac{1}{a} \\
\lambda_1 &=  \frac{1}{a} \\
\lambda_2 &=  0
\end{align*}

The weights of the minimum variance portfolio:

\begin{align*}
w_g & = \lambda_1 \Sigma^{-1} \ones \\
& = \frac{\Sigma^{-1} \ones}{\onesT \Sigma^{-1} \ones}
\end{align*}


+ $\lambda_1 = 0$

This second solution gives $\lambda_2 = \frac{1}{b}$ and the optimal weights:

\begin{align*}
w_d & = \lambda_2 \Sigma^{-1} R \\
& = \frac{\Sigma^{-1} R}{\onesT \Sigma^{-1} R}
\end{align*}


\begin{thm}\label{thm:mv-1}
Any MV optimal portfolio $w^*_P$ with expected excess return $R_P$ can be decomposed into two MV portfolios.

$$
w^*_P = A w_g + (1-A) w_d
$$
\end{thm}

\begin{proof}
Since $w_P$ is MV optimal,
\begin{align*}
w_P &= \lambda_1 \Sigma^{-1} \ones + \lambda_2 \Sigma^{-1} R \\
&= \lambda_1 a w_g + \lambda_2 b w_d
\end{align*}

One can verify that
$$
\lambda_1 a  + \lambda_2 b = 1
$$
\end{proof}

## MV model with riskless asset

The tangency portfolio corresponds to the point on the efficient frontier where the
slope of the tangent $\frac{R_M - r_f}{\sigma_M}$ is maximized, where:

$$
\frac{R_M - r_f}{\sigma_M} = \frac{w^T (R - R_f)}{\sqrt{w^T \Sigma w}}
$$

Noting that the slope is unchanged when the weights $w$ are multiplied by a constant, the tangency portfolio is found by solving the following QP problem for an arbitrary $R^*>R_f$:

$$
\begin{aligned}
    \mbox{min} \ \ & \frac{1}{2} w^T \Sigma w  \\
    \mbox{s.t.} & \\
        \tilde{R}^Tw & = R^*
  \end{aligned}
$$

with $\tilde{R} = R-R_f$.

Lagrangian:

$$
L(w, \lambda) = \frac{1}{2} w^T \Sigma w - \lambda \left(\tilde{R}^Tw - R^* \right)
$$

Which yields:

\begin{equation}
w^* = \lambda^* \Sigma^{-1} \tilde{R}
\label{eq:w-star}
\end{equation}

Normalize so that the weights sum to 1:

\begin{equation}
w^* = \frac{\Sigma^{-1} \tilde{R}}{\onesT \Sigma^{-1} \tilde{R}}
\label{eq:sharpe}
\end{equation}

The corresponding expected excess return is given by:

$$
E(R^*_P) = \frac{\tilde{R}^T \Sigma^{-1} \tilde{R}}{\onesT \Sigma^{-1} \tilde{R}}
$$


## Maximum Sharpe ratio for two risky assets

Given two assets, A and M, the allocation that maximizes the Sharpe ratio is given by:

\begin{equation}
w_A = \frac{R_A \sigma^2_M - R_M \sigma_A \sigma_M \rho_{AM}}{R_A \sigma^2_M + R_M \sigma^2_A - (R_A+R_M) \sigma_A \sigma_M \rho_{AM}}
\label{eq:wA}
\end{equation}

\begin{proof}
Use equation (\ref{eq:sharpe}) with 
\begin{equation}
\Sigma = \begin{bmatrix} \sigma^2_A & \rho \sigma_A \sigma_M \\ \rho \sigma_A \sigma_M & \sigma^2_M \end{bmatrix}
\label{eq:sigma}
\end{equation}

$$
\Sigma^{-1} = \frac{1}{(1-\rho^2) \sigma^2_A\sigma^2_M} \begin{bmatrix} \sigma^2_M & -\rho \sigma_A \sigma_M \\ -\rho \sigma_A \sigma_M & \sigma^2_A \end{bmatrix}
$$
\end{proof}

# Treynor-Black Model [@Treynor1973]

Assets excess return is modeled by a single factor model:

$$
R_i = \alpha_i + \beta_i R_M + e_i
$$

where $\alpha_i$ is the idiosyncratic excess return of asset $i$, and $e_i \sim N(0, \sigma^2_i)$ is the specific risk. 

## Calculation of the active portfolio

The active portfolio is determined by the idiosyncratic excess return and the specific risk of each asset.

The specific risks are assumed to be independent:

$$
\Sigma_A = \begin{bmatrix}
\sigma^2(e_1) & & \\
& \ddots & \\
& & \sigma^2(e_n) \end{bmatrix}
$$

Using equation (\ref{eq:sharpe}), we get:

$$
w_{Ai} = \frac{\sfrac{\alpha_i}{\sigma^2_i}}{\sum \sfrac{\alpha_i}{\sigma^2_i} }
$$

So that the active portfolio has an excess return and variance given by:
\begin{align*}
R_A &= \alpha_A + \beta_A R_M \\
\sigma^2_A &= \beta^2_A \sigma^2_M + \sigma^2(e_A)
\end{align*}

with
\begin{align*}
\alpha_A &= \sum w_{Ai} \alpha_i \\
\beta_A &= \sum w_{Ai} \beta_i \\
\sigma^2(e_A) &= \sum w^2_{Ai} \sigma^2(e_i)
\end{align*}

## Allocation of wealth between the active portfolio and the market portfolio

A fraction $w_A$ of wealth is allocated to the active portfolio, and the balance $(1-w_A)$ to the market portfolio so as to maximize the Sharpe ratio of the global portfolio $xA + (1-x)M$.

Using equation (\ref{eq:wA}) we get after some algebra:

$$
w_A = \frac{\alpha_A \sigma^2_M}{\alpha_A \sigma^2_M(1-\beta_A) + R_M \sigma^2(e_A)}
$$

## Separability of the Sharpe ratio in the active portfolio


The first order condition for the optimal active portfolio is:

\begin{equation}
w_A = \lambda_A \Sigma^{-1} \alpha
\label{eq:FOC-1}
\end{equation}

Substitute in the expression

$$
\alpha_A = w^T_A \alpha
$$

to get:

\begin{equation}
\frac{\alpha_A}{\lambda_A} = \alpha^T \Sigma^{-1} \alpha
\label{eq:sep-1}
\end{equation}

We next get an expression for $\lambda_A$ in terms of known quantities:

\begin{align*}
\sigma^2(e_A) &= w^T_A \Sigma w_A \\
&= \lambda^2_A \alpha^T \Sigma^{-1}\Sigma\Sigma^{-1} \alpha \\
&= \lambda^2_A \alpha^T \Sigma^{-1} \alpha
\end{align*}

Therefore,

\begin{align*}
\frac{\sigma^2(e_A)}{\lambda^2_A} &= \alpha^T \Sigma^{-1} \alpha \\
&= \frac{\alpha_A}{\lambda_A}
\end{align*}

Which yields:

$$
\lambda_A = \frac{\sigma^2(e_A)}{\alpha_A}
$$

Use this result in equation (\ref{eq:sep-1}) to get:

\begin{align*}
\frac{\alpha^2_A}{\sigma^2(e_A)} &= \alpha^T \Sigma^{-1} \alpha \\
&= \sum_i \frac{\alpha^2_i}{\sigma^2(e_i)}
\label{eq:sep-2}
\end{align*}

which shows that the square of the Sharpe ratio of the active portfolio is the sum of the squares of the Sharpe ratios of the assets forming that portfolio.


## The Treynor-Black model in the notation of the 1973 paper and separability of the Sharpe ratio between the active and market portfolios

The investment universe is composed of $n$ assets with asset-specific excess return:

\begin{align}
r_i &= \alpha_i + \beta_i r_M + e_i \ \ i=1, \ldots, n \\
E(r_i) &= \alpha_i + \beta_i E(r_M) = \mu_i
\label{eq:treynor-black-1}
\end{align}

and of the market asset itself. Let $w_i, i=1, \ldots, n$ be the investment in the assets with asset-specific excess returns, and $w_M$ the investment in the market asset.

Treynor and Black restate this portfolio as an investment in $n+1$ assets, asset 1 to $n$ being only exposed to the specific risk, and the $n+1$ asset being only exposed to the market risk:

$$
w_{n+1} = w_M + \sum_{i=1}^n \beta_i w_i
$$

Note that these $n+1$ assets are independent. The mean and variance of the portfolio are:

\begin{align}
E(r_P) &= \sum_{i=1}^{n+1} w_i E(r_i) = \mu_P \\
\sigma^2_P &= \sum_{i=1}^{n+1} w^2_i \sigma^2_i
\end{align}


As usual, maximize the Sharpe ratio by solving:

$$
\begin{aligned}
    \mbox{min} \ \ & \frac{1}{2} w^T \Sigma w  \\
    \mbox{s.t.} & \\
        \mu^Tw & = \mu_P
  \end{aligned}
$$

Keeping in mind that the assets are independent, the Lagrangian is:

$$
L(w, \lambda) = \sum_{i=1}^{n+1} w^2_i \sigma^2_i - 2\lambda \left( \sum_{i=1}^{n+1} w_i \mu_i - \mu_P \right)
$$

First order conditions for optimality yield:

$$
2 w_i \sigma^2_i - 2 \lambda \mu_i = 0 \ \ \ \ i=1, \ldots , n+1
$$

or,

\begin{equation}
w_i = \lambda \frac{\mu_i}{\sigma^2_i}
\label{eq:wi}
\end{equation}

Substitute in (\ref{eq:treynor-black-1}) to get:

\begin{align}
\mu_P &= \lambda \sum_{i=1}^{n+1} \sfrac{\mu^2_i}{\sigma^2_i} \label{eq:lambda-1} \\
\sigma^2_P &= \lambda^2 \sum_{i=1}^{n+1} \mu^2_i \sigma^2_i   \label{eq:lambda-2}
\end{align}

so that,

$$
\lambda = \frac{\sigma^2_P}{\mu_P}
$$

To summarize, the weights of the assets in the active portfolio are:

$$
w_i = \frac{\mu_i}{\mu_P} \frac{\sigma^2_P}{\sigma^2_i} \ \ \ i=1, \ldots, n
$$

To determine the investment in the market asset, $w_M$, recall that,

\begin{align}
\mu_{n+1} &= E(r_M) = \mu_M \\
\sigma^2_{n+1} &= \sigma^2_M
\end{align}

Thus,

\begin{align}
w_{n+1} &= \sum_{i=1}^n w_i \beta_i + w_M \\
&= \lambda \frac{\mu_M}{\sigma^2_M}
\end{align}

From equation (\ref{eq:wi}, we have:

$$
\sum_{i=1}^n w_i \beta_i = \lambda \sum_{i=1}^n \frac{\beta_i \mu_i}{\sigma^2_i}
$$

So that the investment in the market asset can be written as

$$
w_M = \lambda \left[ \frac{\mu_M}{\sigma^2_M} - \sum_{i=1}^n \frac{\beta_i \mu_i}{\sigma^2_i} \right]
$$



To establish the separability of the Sharpe ratio between the active and the market portfolios, combine equations (\ref{eq:lambda-1}) and (\ref{eq:lambda-2}) to get:

$$
\frac{\mu^2_P}{\sigma^2_P} = \sum_{i=1}^{n+1} \frac{\mu^2_i}{\sigma^2_i}
$$

Denoting $S_A, S_M, S_P$ the Sharpe ratios of, respectively, the active, market and overall portfolios, we can restate the previous equation as:

\begin{align}
S^2_P &= \sum_{i=1}^{n} \frac{\mu^2_i}{\sigma^2_i} + S^2_M \\
&= \frac{\alpha^2_A}{\sigma^2_A + S^2_M} \\
S^2_A + S^2_M
\end{align}

Treynor and Black call $\alpha_A = \sum_{i=1}^n w_i \alpha_i$ the "appraisal premium" and $\sigma^2_A = \sum_{i=1}^n w^2_i \sigma^2_i$ the "appraisal risk".   


# Bibliography



